### ISSUE TITLE
(Sorry for making another issue) Invalid command issue

### ISSUE THREAD

**Issue by Clyde-Timonera** [GeyserExtras/GeyserExtras#2]
The ge menu buttons or emote bindings send invalid commands.
![image](https://github.com/GeyserExtras/GeyserExtras/assets/78290310/fef0e4a7-4b98-4a4a-a07b-f35172388881)

**Comment by letsgoawaydev** [comment]
Yeah this is a known issue on proxy, not sure what i can do about it. keeping this issue open but i think its some weird permissions issue on proxy

**Comment by Clyde-Timonera** [comment]
I have heard of permission issues before, but it has been resolved using luckperms and typing them out manually works, seems like some weird bedrock bug

**Comment by onebeastchris** [comment]
That's not a weird bedrock bug, but rather just that proxies do not have a permission system. To use commands from proxy plugins on backend servers, you'll need to install luckperms on the proxy & give users the permission to use those commands there (for velocity, using `/luckpermsv`, or `/luckpermsb` for bungee). See https://wiki.geysermc.org/geyser/commands/ for info on which permissions to add.

**Comment by Clyde6790pGIT** [comment]
> That's not a weird bedrock bug, but rather just that proxies do not have a permission system. To use commands from proxy plugins on backend servers, you'll need to install luckperms on the proxy & give users the permission to use those commands there (for velocity, using `/luckpermsv`, or `/luckpermsb` for bungee). See https://wiki.geysermc.org/geyser/commands/ for info on which permissions to add.

I do use luckperms on velocity and allowed all access to geyser commands (expect admin permissions obviously) and it is still the same.

**Comment by letsgoawaydev** [comment]
GeyserExtras 2.0 will most likely fix this by using Geysers API instead of commands to swap offhand as it will run natively on the proxy instead of proxy-mode. The reason why this happens is because its running the commands on the backend server, and not the proxy itself which Geyser is installed on.
